package com.artica.telesalud.tph.android.mapper;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import org.springframework.http.converter.HttpMessageConverter;
import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter;

public class DateObjectMapper extends ObjectMapper {

    private static MappingJackson2HttpMessageConverter converter;
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    public DateObjectMapper() {
        //the date generated by the converter is in format
        configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    }

    public static HttpMessageConverter getConverter() {
        if (converter == null) {
            converter = new MappingJackson2HttpMessageConverter();
            converter.setObjectMapper(new DateObjectMapper());
        }
        return converter;
    }
}